version: '3.8'

services:
  mysql_db:
    image: mysql:8
    container_name: proyecto_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sh1r0Ya2@
      MYSQL_DATABASE: proyecto_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: Sh1r0Ya2@
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
