# Generated by Django 5.2.8 on 2025-11-16 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_administrador_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contraseña',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='La contraseña debe tener entre 5 y 25 caracteres y puede contener letras, números y caracteres especiales válidos.', regex='^[A-Za-z0-9!@#$%^&*()_\\-+=\\[\\]{};:,.<>?/|~`]{5,25}$')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='contrasena',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='La contraseña debe tener entre 5 y 25 caracteres y puede contener letras, números y caracteres especiales válidos.', regex='^[A-Za-z0-9!@#$%^&*()_\\-+=\\[\\]{};:,.<>?/|~`]{5,25}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contrasena',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='La contraseña debe tener entre 5 y 25 caracteres y puede contener letras, números y caracteres especiales válidos.', regex='^[A-Za-z0-9!@#$%^&*()_\\-+=\\[\\]{};:,.<>?/|~`]{5,25}$')]),
        ),
    ]
