# Generated by Django 5.2.8 on 2025-11-16 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_administrador_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='apellidos',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='contraseña',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener entre 5 y 25 caracteres y puede contener letras, números y caracteres especiales válidos.', regex='^[A-Za-z0-9!@#$%^&*()_\\-+=\\[\\]{};:,.<>?/|~`]{5,25}$')]),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='correo_electronico',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='hora',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='La hora debe estar en formato HH:MM.', regex='^(?:[01]\\d|2[0-3]):[0-5]\\d$')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='apellidos',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='contrasena',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener entre 5 y 25 caracteres y puede contener letras, números y caracteres especiales válidos.', regex='^[A-Za-z0-9!@#$%^&*()_\\-+=\\[\\]{};:,.<>?/|~`]{5,25}$')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contrasena',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener entre 5 y 25 caracteres y puede contener letras, números y caracteres especiales válidos.', regex='^[A-Za-z0-9!@#$%^&*()_\\-+=\\[\\]{};:,.<>?/|~`]{5,25}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo_electronico',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='diagnostico',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
