# Generated by Django 5.2.8 on 2025-11-16 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_administrador_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='estado_cita',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada'), ('Confirmada', 'Confirmada')], default='Pendiente', max_length=45),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='diagnostico',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
