# Generated by Django 5.2.8 on 2025-11-17 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_citamedica_estado_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contraseña',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener entre 5 y 25 caracteres; esta puede contener letras, números y caracteres especiales.', regex='^[A-Za-z0-9!@#$%^&*()_\\-+=\\[\\]{};:,.<>?/|~`]{5,25}$')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='contrasena',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener entre 5 y 25 caracteres; esta puede contener letras, números y caracteres especiales.', regex='^[A-Za-z0-9!@#$%^&*()_\\-+=\\[\\]{};:,.<>?/|~`]{5,25}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contrasena',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener entre 5 y 25 caracteres; esta puede contener letras, números y caracteres especiales.', regex='^[A-Za-z0-9!@#$%^&*()_\\-+=\\[\\]{};:,.<>?/|~`]{5,25}$')]),
        ),
    ]
